twist_mux:
  ros__parameters:
    topics:
      behavior:
        topic: behavior_vel
        timeout: 0.5
        priority: 10
      navigation:
        topic: nav_vel
        timeout: 0.5
        priority: 20
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 100
    locks:
      pause:
        topic: pause_vel
        timeout: 0.0
        priority: 100
      joystick:
        topic: joy_priority
        timeout: 0.0
        priority: 100
        