camera:
   camera:
      ros__parameters:
         device_type: ''
         serial_no: ''
         usb_port_id: ''
         
         color_fps: 30.0
         color_height: 480
         color_width: 848
         color_qos: "SYSTEM_DEFAULT"
         
         depth_fps: 30.0
         depth_height: 480
         depth_width: 848
         depth_qos: "SYSTEM_DEFAULT"
         
         infra_fps: 30.0
         infra_height: 480
         infra_width: 848
         infra_qos: "SYSTEM_DEFAULT"

         accel_fps: 0.0         
         gyro_fps: 0.0
         
         enable_accel: true
         enable_color: true
         enable_depth: true
         enable_gyro: true
         enable_infra1: true
         enable_infra2: false
         
         enable_pointcloud: false
         filters: ''
         
         align_depth: true
         enable_sync: true
         
         pointcloud_texture_index: 0
         pointcloud_texture_stream: RS2_STREAM_COLOR
         
         stereo_module.emitter_enabled: 1
         
         unite_imu_method: 'linear_interpolation'
         initial_reset: true
