rocket_kaya_teleop:
  ros__parameters:
    drive_holonomic:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: cmd_vel
      deadman_buttons: [4]
      axis_mappings:
        twist-linear-x:
          axis: 4
          scale: 1.0
          offset: 0
        twist-linear-y:
          axis: 3
          scale: 1.0
          offset: 0
        twist-angular-z:
          axis: 0
          scale: 1.0
          offset: 0
        header-frame_id:
          value: 'base_link'
